// Mock data for Dragon Street Food Hlohovec
// Modern street food: burgers, kebabs, pinsa, hot dogs, wraps, cheese snacks, desserts

export interface MenuCategoryData {
  id: string
  name: string
  nameSk: string
  slug: string
  description: string
  image: string
  sortOrder: number
}

export interface MenuItemData {
  id: string
  categoryId: string
  name: string
  nameSk: string
  description: string
  descriptionSk: string
  price: number
  image: string
  isPopular: boolean
  isSpicy: boolean
  isNew: boolean
  isVegetarian: boolean
  isAvailable: boolean
  allergens: string[]
  weight: string
  isAlcohol: boolean
  isDailyMenu: boolean
  isWeeklySpecial: boolean
  isDailyDeal: boolean
  addons: MenuAddonData[]
}

export interface MenuAddonData {
  id: string
  name: string
  nameSk: string
  price: number
  isAvailable: boolean
  isModifier?: boolean
  modifierGroup?: string
}

// ─── Categories (24) ──────────────────────────────────────────────────────────

export const categories: MenuCategoryData[] = [
  {
    id: 'cat-1',
    name: 'Najviac objednávané',
    nameSk: 'Najviac objednávané',
    slug: 'najviac-objednavane',
    description: 'Naše najobľúbenejšie jedlá, ktoré si objednávate najčastejšie',
    image: '/images/burger.jpg',
    sortOrder: 1,
  },
  {
    id: 'cat-2',
    name: 'Týždenný špeciál',
    nameSk: 'Týždenný špeciál',
    slug: 'tyzdenny-special',
    description: 'Špeciálna ponuka tejto týždňa – len na obmedzený čas!',
    image: '/images/burger.jpg',
    sortOrder: 2,
  },
  {
    id: 'cat-3',
    name: 'Denné menu',
    nameSk: 'Denné menu',
    slug: 'denne-menu',
    description: 'Kompletné denné menu s polievkou a nápojom',
    image: '/images/menu-box.jpg',
    sortOrder: 3,
  },
  {
    id: 'cat-4',
    name: 'Polievka dňa',
    nameSk: 'Polievka dňa',
    slug: 'polievka-dna',
    description: 'Denne meniaca sa polievka z čerstvých surovín',
    image: '/images/hero-bg.jpg',
    sortOrder: 4,
  },
  {
    id: 'cat-5',
    name: 'Akcia dňa',
    nameSk: 'Akcia dňa',
    slug: 'akcia-dna',
    description: 'Dnešná akčná ponuka za skvelú cenu',
    image: '/images/burger.jpg',
    sortOrder: 5,
  },
  {
    id: 'cat-6',
    name: 'Pinsa',
    nameSk: 'Pinsa',
    slug: 'pinsa',
    description: 'Ľahká a chrumkavá pinsa s vysokým okrajom a prémiovými surovinami',
    image: '/images/pinsa.jpg',
    sortOrder: 6,
  },
  {
    id: 'cat-7',
    name: 'Burgre',
    nameSk: 'Burgre',
    slug: 'burgre',
    description: 'Šťavnaté ručne formované burgre z čerstvého hovädzieho mäsa',
    image: '/images/burger.jpg',
    sortOrder: 7,
  },
  {
    id: 'cat-8',
    name: 'Mini burgre',
    nameSk: 'Mini burgre',
    slug: 'mini-burgre',
    description: 'Menšie burgre ideálne na ochutnanie alebo ako príloha',
    image: '/images/burger.jpg',
    sortOrder: 8,
  },
  {
    id: 'cat-9',
    name: 'Hot dog',
    nameSk: 'Hot dog',
    slug: 'hot-dog',
    description: 'Klasické a špeciálne hot dogy s domácimi údeninami',
    image: '/images/hotdog.jpg',
    sortOrder: 9,
  },
  {
    id: 'cat-10',
    name: 'Kebab',
    nameSk: 'Kebab',
    slug: 'kebab',
    description: 'Tradičný kebab z kvalitného mäsa s domácou omáčkou',
    image: '/images/kebab.jpg',
    sortOrder: 10,
  },
  {
    id: 'cat-11',
    name: 'Kapsalón a krídla',
    nameSk: 'Kapsalón a krídla',
    slug: 'kapsalon-krídla',
    description: 'Kapsalón s hranolkami a kuracie krídla v rôznych omáčkach',
    image: '/images/chicken-wings.jpg',
    sortOrder: 11,
  },
  {
    id: 'cat-12',
    name: 'Mäso',
    nameSk: 'Mäso',
    slug: 'maso',
    description: 'Výberové kúsky mäsa pripravené na grillu',
    image: '/images/chicken-wings.jpg',
    sortOrder: 12,
  },
  {
    id: 'cat-13',
    name: 'Syry',
    nameSk: 'Syry',
    slug: 'syry',
    description: 'Sýrové špeciality – vyprážané, grilované a ako príloha',
    image: '/images/fries.jpg',
    sortOrder: 13,
  },
  {
    id: 'cat-14',
    name: 'Menu box',
    nameSk: 'Menu box',
    slug: 'menu-box',
    description: 'Kompletné boxy s hlavným jedlom, prílohou a nápojom',
    image: '/images/menu-box.jpg',
    sortOrder: 14,
  },
  {
    id: 'cat-15',
    name: 'Tortilly / wrapy',
    nameSk: 'Tortilly / wrapy',
    slug: 'tortilly-wrapy',
    description: 'Plné chuti tortilly a wrapy s čerstvou zeleninou',
    image: '/images/wrap.jpg',
    sortOrder: 15,
  },
  {
    id: 'cat-16',
    name: 'Rodinné combo',
    nameSk: 'Rodinné combo',
    slug: 'rodinne-combo',
    description: 'Veľké porcie pre celú rodinu alebo partičku priateľov',
    image: '/images/menu-box.jpg',
    sortOrder: 16,
  },
  {
    id: 'cat-17',
    name: 'Šaláty',
    nameSk: 'Šaláty',
    slug: 'salaty',
    description: 'Čerstvé šaláty s domácimi dresingmi',
    image: '/images/hero-bg.jpg',
    sortOrder: 17,
  },
  {
    id: 'cat-18',
    name: 'Pre vegánov',
    nameSk: 'Pre vegánov',
    slug: 'pre-veganov',
    description: 'Chutné vegánske alternatívy našich najobľúbenejších jedál',
    image: '/images/hero-bg.jpg',
    sortOrder: 18,
  },
  {
    id: 'cat-19',
    name: 'Špeci ponuka',
    nameSk: 'Špeci ponuka',
    slug: 'speci-ponuka',
    description: 'Exkluzívne jedlá od šéfkuchára a sezónne špeciality',
    image: '/images/burger.jpg',
    sortOrder: 19,
  },
  {
    id: 'cat-20',
    name: 'Mlsky / dezerty',
    nameSk: 'Mlsky / dezerty',
    slug: 'mlsky-dezerty',
    description: 'Sladké pokušenia na záver alebo ako dezert',
    image: '/images/dessert.jpg',
    sortOrder: 20,
  },
  {
    id: 'cat-21',
    name: 'Prílohy',
    nameSk: 'Prílohy',
    slug: 'prilohy',
    description: 'Hranolky, ryža a ďalšie prílohy k vášmu jedlu',
    image: '/images/fries.jpg',
    sortOrder: 21,
  },
  {
    id: 'cat-22',
    name: 'Dresingy',
    nameSk: 'Dresingy',
    slug: 'dresingy',
    description: 'Domáce dresingy a omáčky podľa vášho výberu',
    image: '/images/hero-bg.jpg',
    sortOrder: 22,
  },
  {
    id: 'cat-23',
    name: 'Nápoje',
    nameSk: 'Nápoje',
    slug: 'napoje',
    description: 'Osviežujúce nápoje a pivo k vášmu jedlu',
    image: '/images/hero-bg.jpg',
    sortOrder: 23,
  },
  {
    id: 'cat-24',
    name: 'Nočný rozvoz',
    nameSk: 'Nočný rozvoz',
    slug: 'nocny-rozvoz',
    description: 'Nočný rozvoz po 22:00 – pokiaľ ste hore, my doručíme!',
    image: '/images/burger.jpg',
    sortOrder: 24,
  },
]

// ─── Common Addon Templates ────────────────────────────────────────────────────

const dressingAddons: MenuAddonData[] = [
  { id: 'addon-dressing-1', name: 'Cesnakový', nameSk: 'Cesnakový', price: 0.50, isAvailable: true, isModifier: true, modifierGroup: 'dressing' },
  { id: 'addon-dressing-2', name: 'BBQ', nameSk: 'BBQ', price: 0.50, isAvailable: true, isModifier: true, modifierGroup: 'dressing' },
  { id: 'addon-dressing-3', name: 'Sweet chili', nameSk: 'Sweet chili', price: 0.50, isAvailable: true, isModifier: true, modifierGroup: 'dressing' },
  { id: 'addon-dressing-4', name: 'Sriracha', nameSk: 'Sriracha', price: 0.50, isAvailable: true, isModifier: true, modifierGroup: 'dressing' },
  { id: 'addon-dressing-5', name: 'Ranch', nameSk: 'Ranch', price: 0.50, isAvailable: true, isModifier: true, modifierGroup: 'dressing' },
  { id: 'addon-dressing-6', name: 'Honey mustard', nameSk: 'Honey mustard', price: 0.50, isAvailable: true, isModifier: true, modifierGroup: 'dressing' },
]

const sideAddons: MenuAddonData[] = [
  { id: 'addon-side-1', name: 'Hranolky', nameSk: 'Hranolky', price: 1.50, isAvailable: true, isModifier: true, modifierGroup: 'side' },
  { id: 'addon-side-2', name: 'Belgické hranolky', nameSk: 'Belgické hranolky', price: 2.00, isAvailable: true, isModifier: true, modifierGroup: 'side' },
  { id: 'addon-side-3', name: 'Batátové hranolky', nameSk: 'Batátové hranolky', price: 2.50, isAvailable: true, isModifier: true, modifierGroup: 'side' },
  { id: 'addon-side-4', name: 'Ryža', nameSk: 'Ryža', price: 1.50, isAvailable: true, isModifier: true, modifierGroup: 'side' },
]

const extraAddons: MenuAddonData[] = [
  { id: 'addon-extra-1', name: 'Syr navyše', nameSk: 'Syr navyše', price: 1.00, isAvailable: true },
  { id: 'addon-extra-2', name: 'Slanina', nameSk: 'Slanina', price: 1.50, isAvailable: true },
  { id: 'addon-extra-3', name: 'Mäso navyše', nameSk: 'Mäso navyše', price: 2.00, isAvailable: true },
]

const spiceAddons: MenuAddonData[] = [
  { id: 'addon-spice-1', name: 'Mierne', nameSk: 'Mierne', price: 0.00, isAvailable: true, isModifier: true, modifierGroup: 'spice_level' },
  { id: 'addon-spice-2', name: 'Stredne', nameSk: 'Stredne', price: 0.00, isAvailable: true, isModifier: true, modifierGroup: 'spice_level' },
  { id: 'addon-spice-3', name: 'Pálivé', nameSk: 'Pálivé', price: 0.00, isAvailable: true, isModifier: true, modifierGroup: 'spice_level' },
]

const menuDrinkAddons: MenuAddonData[] = [
  { id: 'addon-drink-1', name: 'Coca-Cola', nameSk: 'Coca-Cola', price: 1.50, isAvailable: true, isModifier: true, modifierGroup: 'drink' },
  { id: 'addon-drink-2', name: 'Sprite', nameSk: 'Sprite', price: 1.50, isAvailable: true, isModifier: true, modifierGroup: 'drink' },
  { id: 'addon-drink-3', name: 'Fuze Tea', nameSk: 'Fuze Tea', price: 1.50, isAvailable: true, isModifier: true, modifierGroup: 'drink' },
]

// ─── Menu Items ────────────────────────────────────────────────────────────────

export const menuItems: MenuItemData[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // cat-1: Najviac objednávané (top 5)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-1',
    categoryId: 'cat-1',
    name: 'Dragon Burger',
    nameSk: 'Dragon Burger',
    description: 'Náš bestseller – ručne formovaný hovädzí burger s cheddarom, slaninou, kyslou uhorkou a domácou BBQ omáčkou',
    descriptionSk: 'Náš bestseller – ručne formovaný hovädzí burger s cheddarom, slaninou, kyslou uhorkou a domácou BBQ omáčkou',
    price: 9.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '10'],
    weight: '320g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-2',
    categoryId: 'cat-1',
    name: 'Kebab v chlebe',
    nameSk: 'Kebab v chlebe',
    description: 'Tradičný kebab v chrumkavom chlebe s čerstvou zeleninou a cesnakovým dresingom',
    descriptionSk: 'Tradičný kebab v chrumkavom chlebe s čerstvou zeleninou a cesnakovým dresingom',
    price: 7.50,
    image: '/images/kebab.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons, ...extraAddons],
  },
  {
    id: 'item-3',
    categoryId: 'cat-1',
    name: 'Pinsa Quattro Formaggi',
    nameSk: 'Pinsa Quattro Formaggi',
    description: 'Ľahká pinsa so štyrmi druhmi syra – mozzarella, gorgonzola, parmezán a ementál',
    descriptionSk: 'Ľahká pinsa so štyrmi druhmi syra – mozzarella, gorgonzola, parmezán a ementál',
    price: 10.90,
    image: '/images/pinsa.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '380g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons],
  },
  {
    id: 'item-4',
    categoryId: 'cat-1',
    name: 'Kuracie krídla BBQ',
    nameSk: 'Kuracie krídla BBQ',
    description: 'Chrumkavé kuracie krídla v sladkej BBQ omáčke s hranolkami',
    descriptionSk: 'Chrumkavé kuracie krídla v sladkej BBQ omáčke s hranolkami',
    price: 8.50,
    image: '/images/chicken-wings.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '400g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-5',
    categoryId: 'cat-1',
    name: 'Chili Cheese Dog',
    nameSk: 'Chili Cheese Dog',
    description: 'Hot dog s chilli con carne, čedarom a jarnou cibuľkou',
    descriptionSk: 'Hot dog s chilli con carne, čedarom a jarnou cibuľkou',
    price: 6.90,
    image: '/images/hotdog.jpg',
    isPopular: true,
    isSpicy: true,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '10'],
    weight: '280g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons, ...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-2: Týždenný špeciál
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-6',
    categoryId: 'cat-2',
    name: 'Burger mesiaca – Truffle Burger',
    nameSk: 'Burger mesiaca – Truffle Burger',
    description: 'Hovädzí burger s truffle majonézou, rukolou a sušenými paradajkami – len tento týždeň!',
    descriptionSk: 'Hovädzí burger s truffle majonézou, rukolou a sušenými paradajkami – len tento týždeň!',
    price: 12.90,
    image: '/images/burger.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '340g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: true,
    isDailyDeal: false,
    addons: [...sideAddons, ...extraAddons],
  },
  {
    id: 'item-7',
    categoryId: 'cat-2',
    name: 'Týždenný kebab špeciál',
    nameSk: 'Týždenný kebab špeciál',
    description: 'Kebab s marockou harissa omáčkou a grilovanou zeleninou',
    descriptionSk: 'Kebab s marockou harissa omáčkou a grilovanou zeleninou',
    price: 8.90,
    image: '/images/kebab.jpg',
    isPopular: false,
    isSpicy: true,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '370g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: true,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-8',
    categoryId: 'cat-2',
    name: 'Pinsa Prosciutto e Rucola',
    nameSk: 'Pinsa Prosciutto e Rucola',
    description: 'Pinsa s prosciuttom, rukolou, parmezánom a balzamikovým krémom',
    descriptionSk: 'Pinsa s prosciuttom, rukolou, parmezánom a balzamikovým krémom',
    price: 13.50,
    image: '/images/pinsa.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '390g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: true,
    isDailyDeal: false,
    addons: [...extraAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-3: Denné menu
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-9',
    categoryId: 'cat-3',
    name: 'Denné menu: Burger + polievka + nápoj',
    nameSk: 'Denné menu: Burger + polievka + nápoj',
    description: 'Klasický cheeseburger, polievka dňa a nápoj podľa výberu',
    descriptionSk: 'Klasický cheeseburger, polievka dňa a nápoj podľa výberu',
    price: 9.90,
    image: '/images/menu-box.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '550g',
    isAlcohol: false,
    isDailyMenu: true,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...spiceAddons],
  },
  {
    id: 'item-10',
    categoryId: 'cat-3',
    name: 'Denné menu: Kebab + polievka + nápoj',
    nameSk: 'Denné menu: Kebab + polievka + nápoj',
    description: 'Kebab v chlebe, polievka dňa a nápoj podľa výberu',
    descriptionSk: 'Kebab v chlebe, polievka dňa a nápoj podľa výberu',
    price: 8.90,
    image: '/images/menu-box.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '580g',
    isAlcohol: false,
    isDailyMenu: true,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-11',
    categoryId: 'cat-3',
    name: 'Denné menu: Pinsa + polievka + nápoj',
    nameSk: 'Denné menu: Pinsa + polievka + nápoj',
    description: 'Pinsa Margherita, polievka dňa a nápoj podľa výberu',
    descriptionSk: 'Pinsa Margherita, polievka dňa a nápoj podľa výberu',
    price: 10.90,
    image: '/images/menu-box.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '600g',
    isAlcohol: false,
    isDailyMenu: true,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...extraAddons],
  },
  {
    id: 'item-12',
    categoryId: 'cat-3',
    name: 'Denné menu: Wrap + polievka + nápoj',
    nameSk: 'Denné menu: Wrap + polievka + nápoj',
    description: 'Kurací wrap s zeleninou, polievka dňa a nápoj podľa výberu',
    descriptionSk: 'Kurací wrap s zeleninou, polievka dňa a nápoj podľa výberu',
    price: 8.50,
    image: '/images/menu-box.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '520g',
    isAlcohol: false,
    isDailyMenu: true,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...dressingAddons, ...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-4: Polievka dňa
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-13',
    categoryId: 'cat-4',
    name: 'Polievka dňa',
    nameSk: 'Polievka dňa',
    description: 'Denne meniaca sa domáca polievka – opýtajte sa personálu na dnešnú',
    descriptionSk: 'Denne meniaca sa domáca polievka – opýtajte sa personálu na dnešnú',
    price: 3.50,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '9'],
    weight: '300ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-14',
    categoryId: 'cat-4',
    name: 'Gulášová polievka',
    nameSk: 'Gulášová polievka',
    description: 'Hustá gulášová polievka s kúskami mäsa a zemiakmi',
    descriptionSk: 'Hustá gulášová polievka s kúskami mäsa a zemiakmi',
    price: 4.20,
    image: '/images/hero-bg.jpg',
    isPopular: true,
    isSpicy: true,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '9'],
    weight: '350ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...spiceAddons],
  },
  {
    id: 'item-15',
    categoryId: 'cat-4',
    name: 'Paradajková polievka',
    nameSk: 'Paradajková polievka',
    description: 'Krémová paradajková polievka s bazalkou a krutónmi',
    descriptionSk: 'Krémová paradajková polievka s bazalkou a krutónmi',
    price: 3.90,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '300ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-5: Akcia dňa
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-16',
    categoryId: 'cat-5',
    name: '2x Mini burger + hranolky',
    nameSk: '2x Mini burger + hranolky',
    description: 'Dva mini cheeseburgre s hranolkami za akčnú cenu',
    descriptionSk: 'Dva mini cheeseburgre s hranolkami za akčnú cenu',
    price: 8.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '450g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: true,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-17',
    categoryId: 'cat-5',
    name: 'Kebab + nápoj',
    nameSk: 'Kebab + nápoj',
    description: 'Kebab v chlebe s nápojom podľa výberu',
    descriptionSk: 'Kebab v chlebe s nápojom podľa výberu',
    price: 8.50,
    image: '/images/kebab.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '500g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: true,
    addons: [...menuDrinkAddons, ...dressingAddons],
  },
  {
    id: 'item-18',
    categoryId: 'cat-5',
    name: 'Pinsa + 2 nápoje',
    nameSk: 'Pinsa + 2 nápoje',
    description: 'Ľubovoľná pinsa s dvoma nápojmi za výhodnú cenu',
    descriptionSk: 'Ľubovoľná pinsa s dvoma nápojmi za výhodnú cenu',
    price: 12.90,
    image: '/images/pinsa.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '550g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: true,
    addons: [...menuDrinkAddons, ...extraAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-6: Pinsa
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-19',
    categoryId: 'cat-6',
    name: 'Pinsa Margherita',
    nameSk: 'Pinsa Margherita',
    description: 'Klasická pinsa s paradajkovým základom, mozzarellou a bazalkou',
    descriptionSk: 'Klasická pinsa s paradajkovým základom, mozzarellou a bazalkou',
    price: 8.90,
    image: '/images/pinsa.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons],
  },
  {
    id: 'item-20',
    categoryId: 'cat-6',
    name: 'Pinsa Prosciutto',
    nameSk: 'Pinsa Prosciutto',
    description: 'Pinsa s prosciuttom, rukolou a parmezánom',
    descriptionSk: 'Pinsa s prosciuttom, rukolou a parmezánom',
    price: 11.90,
    image: '/images/pinsa.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '370g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons],
  },
  {
    id: 'item-21',
    categoryId: 'cat-6',
    name: 'Pinsa Diavola',
    nameSk: 'Pinsa Diavola',
    description: 'Pikantná pinsa s salámou piccante, čili a červenou cibuľou',
    descriptionSk: 'Pikantná pinsa s salámou piccante, čili a červenou cibuľou',
    price: 10.90,
    image: '/images/pinsa.jpg',
    isPopular: false,
    isSpicy: true,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '360g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-22',
    categoryId: 'cat-6',
    name: 'Pinsa Quattro Formaggi',
    nameSk: 'Pinsa Quattro Formaggi',
    description: 'Ľahká pinsa so štyrmi druhmi syra – mozzarella, gorgonzola, parmezán a ementál',
    descriptionSk: 'Ľahká pinsa so štyrmi druhmi syra – mozzarella, gorgonzola, parmezán a ementál',
    price: 10.90,
    image: '/images/pinsa.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '380g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons],
  },
  {
    id: 'item-23',
    categoryId: 'cat-6',
    name: 'Pinsa Caprese',
    nameSk: 'Pinsa Caprese',
    description: 'Pinsa s čerstvou mozzarellou, paradajkami a balzamikovým krémom',
    descriptionSk: 'Pinsa s čerstvou mozzarellou, paradajkami a balzamikovým krémom',
    price: 9.90,
    image: '/images/pinsa.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '360g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-7: Burgre
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-24',
    categoryId: 'cat-7',
    name: 'Classic Cheeseburger',
    nameSk: 'Classic Cheeseburger',
    description: 'Hovädží burger s cheddarom, kyslou uhorkou, cibuľou a kečupom',
    descriptionSk: 'Hovädží burger s cheddarom, kyslou uhorkou, cibuľou a kečupom',
    price: 7.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '280g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...extraAddons],
  },
  {
    id: 'item-25',
    categoryId: 'cat-7',
    name: 'Dragon Burger',
    nameSk: 'Dragon Burger',
    description: 'Ručne formovaný hovädzí burger s cheddarom, slaninou, kyslou uhorkou a domácou BBQ omáčkou',
    descriptionSk: 'Ručne formovaný hovädzí burger s cheddarom, slaninou, kyslou uhorkou a domácou BBQ omáčkou',
    price: 9.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '10'],
    weight: '320g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-26',
    categoryId: 'cat-7',
    name: 'Double Smash Burger',
    nameSk: 'Double Smash Burger',
    description: 'Dve plátky smash hovädzieho mäsa s americkým syrom a špeciálnou omáčkou',
    descriptionSk: 'Dve plátky smash hovädzieho mäsa s americkým syrom a špeciálnou omáčkou',
    price: 11.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-27',
    categoryId: 'cat-7',
    name: 'Bacon Jalapeño Burger',
    nameSk: 'Bacon Jalapeño Burger',
    description: 'Hovädzí burger so slaninou, jalapeño, pepper jack syrom a chipotle majonézou',
    descriptionSk: 'Hovädží burger so slaninou, jalapeño, pepper jack syrom a chipotle majonézou',
    price: 10.90,
    image: '/images/burger.jpg',
    isPopular: false,
    isSpicy: true,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '330g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-28',
    categoryId: 'cat-7',
    name: 'Chicken Burger',
    nameSk: 'Chicken Burger',
    description: 'Chrumkavý kurací steak s rukolou, paradajkami a cesnakovým dresingom',
    descriptionSk: 'Chrumkavý kurací steak s rukolou, paradajkami a cesnakovým dresingom',
    price: 8.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '300g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-8: Mini burgre
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-29',
    categoryId: 'cat-8',
    name: 'Mini Cheeseburger',
    nameSk: 'Mini Cheeseburger',
    description: 'Menší hovädzí burger s cheddarom a kyslou uhorkou',
    descriptionSk: 'Menší hovädzí burger s cheddarom a kyslou uhorkou',
    price: 4.50,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '150g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons],
  },
  {
    id: 'item-30',
    categoryId: 'cat-8',
    name: 'Mini BBQ Burger',
    nameSk: 'Mini BBQ Burger',
    description: 'Menší burger s BBQ omáčkou a slaninou',
    descriptionSk: 'Menší burger s BBQ omáčkou a slaninou',
    price: 5.20,
    image: '/images/burger.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '160g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons],
  },
  {
    id: 'item-31',
    categoryId: 'cat-8',
    name: 'Mini Chicken Burger',
    nameSk: 'Mini Chicken Burger',
    description: 'Menší kurací burger so šalátom a majonézou',
    descriptionSk: 'Menší kurací burger so šalátom a majonézou',
    price: 4.90,
    image: '/images/burger.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '150g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },
  {
    id: 'item-32',
    categoryId: 'cat-8',
    name: 'Mini Veggie Burger',
    nameSk: 'Mini Veggie Burger',
    description: 'Menší vegánsky burger s fazuľovou plátkou a rukolou',
    descriptionSk: 'Menší vegánsky burger s fazuľovou plátkou a rukolou',
    price: 4.50,
    image: '/images/burger.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '140g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-9: Hot dog
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-33',
    categoryId: 'cat-9',
    name: 'Classic Hot Dog',
    nameSk: 'Classic Hot Dog',
    description: 'Klasický hot dog s kečupom, horčicou a kyslou uhorkou',
    descriptionSk: 'Klasický hot dog s kečupom, horčicou a kyslou uhorkou',
    price: 4.90,
    image: '/images/hotdog.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '10'],
    weight: '200g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-34',
    categoryId: 'cat-9',
    name: 'Chili Cheese Dog',
    nameSk: 'Chili Cheese Dog',
    description: 'Hot dog s chilli con carne, čedarom a jarnou cibuľkou',
    descriptionSk: 'Hot dog s chilli con carne, čedarom a jarnou cibuľkou',
    price: 6.90,
    image: '/images/hotdog.jpg',
    isPopular: true,
    isSpicy: true,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '10'],
    weight: '280g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-35',
    categoryId: 'cat-9',
    name: 'BBQ Bacon Dog',
    nameSk: 'BBQ Bacon Dog',
    description: 'Hot dog so slaninou, BBQ omáčkou a karamelizovanou cibuľou',
    descriptionSk: 'Hot dog so slaninou, BBQ omáčkou a karamelizovanou cibuľou',
    price: 7.50,
    image: '/images/hotdog.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '270g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-36',
    categoryId: 'cat-9',
    name: 'New York Dog',
    nameSk: 'New York Dog',
    description: 'Hot dog s kyslým kapustou, horčicou a paprikou',
    descriptionSk: 'Hot dog s kyslým kapustou, horčicou a paprikou',
    price: 5.90,
    image: '/images/hotdog.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '9', '10'],
    weight: '230g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-10: Kebab
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-37',
    categoryId: 'cat-10',
    name: 'Kebab v chlebe',
    nameSk: 'Kebab v chlebe',
    description: 'Tradičný kebab v chrumkavom chlebe s čerstvou zeleninou a cesnakovým dresingom',
    descriptionSk: 'Tradičný kebab v chrumkavom chlebe s čerstvou zeleninou a cesnakovým dresingom',
    price: 7.50,
    image: '/images/kebab.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons, ...extraAddons],
  },
  {
    id: 'item-38',
    categoryId: 'cat-10',
    name: 'Kebab v tortille',
    nameSk: 'Kebab v tortille',
    description: 'Kebab zabalený v mäkkej tortille so zeleninou a jogurtovým dresingom',
    descriptionSk: 'Kebab zabalený v mäkkej tortille so zeleninou a jogurtovým dresingom',
    price: 7.90,
    image: '/images/kebab.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '340g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons, ...extraAddons],
  },
  {
    id: 'item-39',
    categoryId: 'cat-10',
    name: 'Kebab tančík',
    nameSk: 'Kebab tančík',
    description: 'Kebab na tanieri s hranolkami, zeleninou a omáčkami',
    descriptionSk: 'Kebab na tanieri s hranolkami, zeleninou a omáčkami',
    price: 9.90,
    image: '/images/kebab.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '450g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-40',
    categoryId: 'cat-10',
    name: 'Kebab XXL',
    nameSk: 'Kebab XXL',
    description: 'Extra veľký kebab s dvojitou porciou mäsa a zeleniny',
    descriptionSk: 'Extra veľký kebab s dvojitou porciou mäsa a zeleniny',
    price: 10.90,
    image: '/images/kebab.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '500g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-41',
    categoryId: 'cat-10',
    name: 'Pikantný kebab',
    nameSk: 'Pikantný kebab',
    description: 'Kebab s pikantnou harissa omáčkou a feferónkami',
    descriptionSk: 'Kebab s pikantnou harissa omáčkou a feferónkami',
    price: 8.50,
    image: '/images/kebab.jpg',
    isPopular: false,
    isSpicy: true,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '360g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-11: Kapsalón a krídla
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-42',
    categoryId: 'cat-11',
    name: 'Kapsalón kurací',
    nameSk: 'Kapsalón kurací',
    description: 'Hranolky, kuracie mäso, syr, zelenina a omáčka v jednej porcii',
    descriptionSk: 'Hranolky, kuracie mäso, syr, zelenina a omáčka v jednej porcii',
    price: 10.90,
    image: '/images/chicken-wings.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '500g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-43',
    categoryId: 'cat-11',
    name: 'Kapsalón kebab',
    nameSk: 'Kapsalón kebab',
    description: 'Hranolky, kebab mäso, syr, zelenina a cesnakový dresing',
    descriptionSk: 'Hranolky, kebab mäso, syr, zelenina a cesnakový dresing',
    price: 11.50,
    image: '/images/kebab.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '520g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-44',
    categoryId: 'cat-11',
    name: 'Kuracie krídla BBQ',
    nameSk: 'Kuracie krídla BBQ',
    description: 'Chrumkavé kuracie krídla v sladkej BBQ omáčke',
    descriptionSk: 'Chrumkavé kuracie krídla v sladkej BBQ omáčke',
    price: 8.50,
    image: '/images/chicken-wings.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-45',
    categoryId: 'cat-11',
    name: 'Kuracie krídla Buffalo',
    nameSk: 'Kuracie krídla Buffalo',
    description: 'Pikantné krídla v buffalo omáčke s blue cheese dresingom',
    descriptionSk: 'Pikantné krídla v buffalo omáčke s blue cheese dresingom',
    price: 9.50,
    image: '/images/chicken-wings.jpg',
    isPopular: false,
    isSpicy: true,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-46',
    categoryId: 'cat-11',
    name: 'Kuracie krídla Honey Mustard',
    nameSk: 'Kuracie krídla Honey Mustard',
    description: 'Krídla v sladkej medovo-horčicovej glazúre',
    descriptionSk: 'Krídla v sladkej medovo-horčicovej glazúre',
    price: 8.90,
    image: '/images/chicken-wings.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '10'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-12: Mäso
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-47',
    categoryId: 'cat-12',
    name: 'Grilovaný kurací steak',
    nameSk: 'Grilovaný kurací steak',
    description: 'Grilovaný kurací steak s bylinkami, podávaný s prílohou',
    descriptionSk: 'Grilovaný kurací steak s bylinkami, podávaný s prílohou',
    price: 9.90,
    image: '/images/chicken-wings.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['3', '7'],
    weight: '300g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons],
  },
  {
    id: 'item-48',
    categoryId: 'cat-12',
    name: 'Bravčové rebierka BBQ',
    nameSk: 'Bravčové rebierka BBQ',
    description: 'Pomalé bravčové rebierka v BBQ omáčke s hranolkami',
    descriptionSk: 'Pomalé bravčové rebierka v BBQ omáčke s hranolkami',
    price: 12.90,
    image: '/images/chicken-wings.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['3', '7'],
    weight: '450g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-49',
    categoryId: 'cat-12',
    name: 'Grilovaný flank steak',
    nameSk: 'Grilovaný flank steak',
    description: 'Hovädzí flank steak s chimichurri omáčkou a hranolkami',
    descriptionSk: 'Hovädzí flank steak s chimichurri omáčkou a hranolkami',
    price: 14.90,
    image: '/images/chicken-wings.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['3', '7'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons],
  },
  {
    id: 'item-50',
    categoryId: 'cat-12',
    name: 'Kurací špíz',
    nameSk: 'Kurací špíz',
    description: 'Kurací špíz so zeleninou a ryžou',
    descriptionSk: 'Kurací špíz so zeleninou a ryžou',
    price: 8.90,
    image: '/images/chicken-wings.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['3', '7'],
    weight: '280g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons, ...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-13: Syry
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-51',
    categoryId: 'cat-13',
    name: 'Vyprážaný syr',
    nameSk: 'Vyprážaný syr',
    description: 'Chrumkavý vyprážaný syr s tatárskou omáčkou a hranolkami',
    descriptionSk: 'Chrumkavý vyprážaný syr s tatárskou omáčkou a hranolkami',
    price: 7.90,
    image: '/images/fries.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '300g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons],
  },
  {
    id: 'item-52',
    categoryId: 'cat-13',
    name: 'Camembert vyprážaný',
    nameSk: 'Camembert vyprážaný',
    description: 'Vyprážaný camembert s brusnicovou omáčkou a hranolkami',
    descriptionSk: 'Vyprážaný camembert s brusnicovou omáčkou a hranolkami',
    price: 8.50,
    image: '/images/fries.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '280g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons],
  },
  {
    id: 'item-53',
    categoryId: 'cat-13',
    name: 'Halloumi na grile',
    nameSk: 'Halloumi na grile',
    description: 'Grilovaný halloumi s rukolou a balzamikovým krémom',
    descriptionSk: 'Grilovaný halloumi s rukolou a balzamikovým krémom',
    price: 7.50,
    image: '/images/fries.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['7'],
    weight: '200g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons],
  },
  {
    id: 'item-54',
    categoryId: 'cat-13',
    name: 'Syrové tyčinky',
    nameSk: 'Syrové tyčinky',
    description: 'Chrumkavé syrové tyčinky s kečupom a dresingom',
    descriptionSk: 'Chrumkavé syrové tyčinky s kečupom a dresingom',
    price: 4.90,
    image: '/images/fries.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '180g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-14: Menu box
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-55',
    categoryId: 'cat-14',
    name: 'Burger box',
    nameSk: 'Burger box',
    description: 'Cheeseburger, hranolky a Coca-Cola 0.33l',
    descriptionSk: 'Cheeseburger, hranolky a Coca-Cola 0.33l',
    price: 10.90,
    image: '/images/menu-box.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '550g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...spiceAddons],
  },
  {
    id: 'item-56',
    categoryId: 'cat-14',
    name: 'Kebab box',
    nameSk: 'Kebab box',
    description: 'Kebab v chlebe, hranolky a nápoj 0.33l',
    descriptionSk: 'Kebab v chlebe, hranolky a nápoj 0.33l',
    price: 10.50,
    image: '/images/menu-box.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '600g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...dressingAddons],
  },
  {
    id: 'item-57',
    categoryId: 'cat-14',
    name: 'Krídla box',
    nameSk: 'Krídla box',
    description: 'Kuracie krídla BBQ, hranolky a nápoj 0.33l',
    descriptionSk: 'Kuracie krídla BBQ, hranolky a nápoj 0.33l',
    price: 11.50,
    image: '/images/menu-box.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '550g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-58',
    categoryId: 'cat-14',
    name: 'Syr box',
    nameSk: 'Syr box',
    description: 'Vyprážaný syr, hranolky a nápoj 0.33l',
    descriptionSk: 'Vyprážaný syr, hranolky a nápoj 0.33l',
    price: 9.90,
    image: '/images/menu-box.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '500g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...dressingAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-15: Tortilly / wrapy
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-59',
    categoryId: 'cat-15',
    name: 'Kurací wrap classic',
    nameSk: 'Kurací wrap classic',
    description: 'Kuracie mäso, zelenina, syr a cesnakový dresing v tortille',
    descriptionSk: 'Kuracie mäso, zelenina, syr a cesnakový dresing v tortille',
    price: 7.90,
    image: '/images/wrap.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '300g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-60',
    categoryId: 'cat-15',
    name: 'BBQ wrap',
    nameSk: 'BBQ wrap',
    description: 'Kuracie mäso, slanina, BBQ omáčka a červená cibuľa v tortille',
    descriptionSk: 'Kuracie mäso, slanina, BBQ omáčka a červená cibuľa v tortille',
    price: 8.90,
    image: '/images/wrap.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '320g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-61',
    categoryId: 'cat-15',
    name: 'Sweet chili wrap',
    nameSk: 'Sweet chili wrap',
    description: 'Kuracie mäso so sweet chili omáčkou, rukolou a feta syrom',
    descriptionSk: 'Kuracie mäso so sweet chili omáčkou, rukolou a feta syrom',
    price: 8.50,
    image: '/images/wrap.jpg',
    isPopular: false,
    isSpicy: true,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '310g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-62',
    categoryId: 'cat-15',
    name: 'Veggie wrap',
    nameSk: 'Veggie wrap',
    description: 'Grilovaná zelenina, hummus a rukola v celozrnnej tortille',
    descriptionSk: 'Grilovaná zelenina, hummus a rukola v celozrnnej tortille',
    price: 6.90,
    image: '/images/wrap.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '270g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },
  {
    id: 'item-63',
    categoryId: 'cat-15',
    name: 'Kebab wrap',
    nameSk: 'Kebab wrap',
    description: 'Kebab mäso s čerstvou zeleninou a jogurtovým dresingom v tortille',
    descriptionSk: 'Kebab mäso s čerstvou zeleninou a jogurtovým dresingom v tortille',
    price: 7.90,
    image: '/images/wrap.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '340g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-16: Rodinné combo
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-64',
    categoryId: 'cat-16',
    name: 'Burger combo pre 2',
    nameSk: 'Burger combo pre 2',
    description: '2x Dragon Burger, hranolky a 2x nápoj 0.33l',
    descriptionSk: '2x Dragon Burger, hranolky a 2x nápoj 0.33l',
    price: 22.90,
    image: '/images/menu-box.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '900g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...spiceAddons],
  },
  {
    id: 'item-65',
    categoryId: 'cat-16',
    name: 'Kebab combo pre 2',
    nameSk: 'Kebab combo pre 2',
    description: '2x Kebab v chlebe, hranolky a 2x nápoj 0.33l',
    descriptionSk: '2x Kebab v chlebe, hranolky a 2x nápoj 0.33l',
    price: 20.90,
    image: '/images/menu-box.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '950g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...dressingAddons],
  },
  {
    id: 'item-66',
    categoryId: 'cat-16',
    name: 'Rodinný box pre 4',
    nameSk: 'Rodinný box pre 4',
    description: '4x ľubovoľný burger, 2x hranolky, 4x nápoj 0.33l',
    descriptionSk: '4x ľubovoľný burger, 2x hranolky, 4x nápoj 0.33l',
    price: 39.90,
    image: '/images/menu-box.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '1800g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...spiceAddons],
  },
  {
    id: 'item-67',
    categoryId: 'cat-16',
    name: 'Krídla party box',
    nameSk: 'Krídla party box',
    description: '24 krídiel v BBQ omáčke, 3x hranolky a 3x nápoj 0.33l',
    descriptionSk: '24 krídiel v BBQ omáčke, 3x hranolky a 3x nápoj 0.33l',
    price: 34.90,
    image: '/images/chicken-wings.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '1500g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...menuDrinkAddons, ...dressingAddons, ...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-17: Šaláty
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-68',
    categoryId: 'cat-17',
    name: 'Cézar šalát',
    nameSk: 'Cézar šalát',
    description: 'Klasický cézar šalát s kuracím mäsom, parmezánom a krutónmi',
    descriptionSk: 'Klasický cézar šalát s kuracím mäsom, parmezánom a krutónmi',
    price: 8.90,
    image: '/images/hero-bg.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '8'],
    weight: '320g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...extraAddons],
  },
  {
    id: 'item-69',
    categoryId: 'cat-17',
    name: 'Grécky šalát',
    nameSk: 'Grécky šalát',
    description: 'Čerstvá zelenina s fetou, olivami a extra panenským olivovým olejom',
    descriptionSk: 'Čerstvá zelenina s fetou, olivami a extra panenským olivovým olejom',
    price: 7.50,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['7'],
    weight: '300g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },
  {
    id: 'item-70',
    categoryId: 'cat-17',
    name: 'Šalát s grilovaným halloumi',
    nameSk: 'Šalát s grilovaným halloumi',
    description: 'Mix šalátov s grilovaným halloumi, paradajkami a balzamikovým krémom',
    descriptionSk: 'Mix šalátov s grilovaným halloumi, paradajkami a balzamikovým krémom',
    price: 8.50,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['7'],
    weight: '300g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-18: Pre vegánov
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-71',
    categoryId: 'cat-18',
    name: 'Vegánsky burger',
    nameSk: 'Vegánsky burger',
    description: 'Fazuľová plátka s avokádom, rukolou a vegánskou majonézou',
    descriptionSk: 'Fazuľová plátka s avokádom, rukolou a vegánskou majonézou',
    price: 8.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '290g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-72',
    categoryId: 'cat-18',
    name: 'Veggie wrap',
    nameSk: 'Veggie wrap',
    description: 'Grilovaná zelenina, hummus a rukola v celozrnnej tortille',
    descriptionSk: 'Grilovaná zelenina, hummus a rukola v celozrnnej tortille',
    price: 6.90,
    image: '/images/wrap.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '270g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },
  {
    id: 'item-73',
    categoryId: 'cat-18',
    name: 'Vegánska pinsa',
    nameSk: 'Vegánska pinsa',
    description: 'Pinsa s vegánskym syrom, sušenými paradajkami a bazalkou',
    descriptionSk: 'Pinsa s vegánskym syrom, sušenými paradajkami a bazalkou',
    price: 9.90,
    image: '/images/pinsa.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '350g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...extraAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-19: Špeci ponuka
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-74',
    categoryId: 'cat-19',
    name: 'Dragon Special Burger',
    nameSk: 'Dragon Special Burger',
    description: 'Hovädzí burger s truffle majonézou, rukolou, sušenými paradajkami a tmavým chlebom',
    descriptionSk: 'Hovädzí burger s truffle majonézou, rukolou, sušenými paradajkami a tmavým chlebom',
    price: 13.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '360g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...extraAddons],
  },
  {
    id: 'item-75',
    categoryId: 'cat-19',
    name: 'Kapsalón Premium',
    nameSk: 'Kapsalón Premium',
    description: 'Kapsalón s hovädzím mäsom, truffle hranolkami a parmezánom',
    descriptionSk: 'Kapsalón s hovädzím mäsom, truffle hranolkami a parmezánom',
    price: 14.90,
    image: '/images/chicken-wings.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '550g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-20: Mlsky / dezerty
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-76',
    categoryId: 'cat-20',
    name: 'Churros s čokoládou',
    nameSk: 'Churros s čokoládou',
    description: 'Teplé churros s tekutou belgickou čokoládou',
    descriptionSk: 'Teplé churros s tekutou belgickou čokoládou',
    price: 4.90,
    image: '/images/dessert.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '180g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-77',
    categoryId: 'cat-20',
    name: 'Brownie s zmrzlinou',
    nameSk: 'Brownie s zmrzlinou',
    description: 'Teplý čokoládový brownie s vanilkovou zmrzlinou',
    descriptionSk: 'Teplý čokoládový brownie s vanilkovou zmrzlinou',
    price: 5.90,
    image: '/images/dessert.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7', '8'],
    weight: '200g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-78',
    categoryId: 'cat-20',
    name: 'Langoš s cesnakom',
    nameSk: 'Langoš s cesnakom',
    description: 'Chrumkavý langoš s cesnakovým dresingom a syrom',
    descriptionSk: 'Chrumkavý langoš s cesnakovým dresingom a syrom',
    price: 3.90,
    image: '/images/dessert.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '200g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...extraAddons],
  },
  {
    id: 'item-79',
    categoryId: 'cat-20',
    name: 'Nutella tortilla',
    nameSk: 'Nutella tortilla',
    description: 'Teplá tortilla plnená Nutellou a banánom',
    descriptionSk: 'Teplá tortilla plnená Nutellou a banánom',
    price: 4.50,
    image: '/images/dessert.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7', '8'],
    weight: '160g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-21: Prílohy
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-80',
    categoryId: 'cat-21',
    name: 'Hranolky',
    nameSk: 'Hranolky',
    description: 'Chrumkavé zlaté hranolky',
    descriptionSk: 'Chrumkavé zlaté hranolky',
    price: 2.90,
    image: '/images/fries.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3'],
    weight: '150g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },
  {
    id: 'item-81',
    categoryId: 'cat-21',
    name: 'Belgické hranolky',
    nameSk: 'Belgické hranolky',
    description: 'Hrubšie belgické hranolky s domácou majonézou',
    descriptionSk: 'Hrubšie belgické hranolky s domácou majonézou',
    price: 3.50,
    image: '/images/fries.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '180g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },
  {
    id: 'item-82',
    categoryId: 'cat-21',
    name: 'Batátové hranolky',
    nameSk: 'Batátové hranolky',
    description: 'Sladké batátové hranolky s chipotle majonézou',
    descriptionSk: 'Sladké batátové hranolky s chipotle majonézou',
    price: 3.90,
    image: '/images/fries.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '150g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },
  {
    id: 'item-83',
    categoryId: 'cat-21',
    name: 'Ryža',
    nameSk: 'Ryža',
    description: 'Dusená biela ryža',
    descriptionSk: 'Dusená biela ryža',
    price: 2.50,
    image: '/images/fries.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: [],
    weight: '150g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-84',
    categoryId: 'cat-21',
    name: 'Coleslaw',
    nameSk: 'Coleslaw',
    description: 'Čerstvý kapustový šalát s mrkvou a dresingom',
    descriptionSk: 'Čerstvý kapustový šalát s mrkvou a dresingom',
    price: 2.00,
    image: '/images/fries.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['3', '7', '9'],
    weight: '120g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-22: Dresingy
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-85',
    categoryId: 'cat-22',
    name: 'Cesnakový dresing',
    nameSk: 'Cesnakový dresing',
    description: 'Domáci cesnakový dresing',
    descriptionSk: 'Domáci cesnakový dresing',
    price: 0.50,
    image: '/images/hero-bg.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['3', '7'],
    weight: '30ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-86',
    categoryId: 'cat-22',
    name: 'BBQ omáčka',
    nameSk: 'BBQ omáčka',
    description: 'Sladká údená BBQ omáčka',
    descriptionSk: 'Sladká údená BBQ omáčka',
    price: 0.50,
    image: '/images/hero-bg.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['7', '10'],
    weight: '30ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-87',
    categoryId: 'cat-22',
    name: 'Sweet chili omáčka',
    nameSk: 'Sweet chili omáčka',
    description: 'Sladká chiliová omáčka',
    descriptionSk: 'Sladká chiliová omáčka',
    price: 0.50,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: true,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['7'],
    weight: '30ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-88',
    categoryId: 'cat-22',
    name: 'Sriracha',
    nameSk: 'Sriracha',
    description: 'Pálivá sriracha omáčka',
    descriptionSk: 'Pálivá sriracha omáčka',
    price: 0.50,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: true,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['7', '10'],
    weight: '30ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-89',
    categoryId: 'cat-22',
    name: 'Ranch dresing',
    nameSk: 'Ranch dresing',
    description: 'Krémový ranch dresing',
    descriptionSk: 'Krémový ranch dresing',
    price: 0.50,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['3', '7'],
    weight: '30ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-90',
    categoryId: 'cat-22',
    name: 'Honey mustard',
    nameSk: 'Honey mustard',
    description: 'Medovo-horčicový dresing',
    descriptionSk: 'Medovo-horčicový dresing',
    price: 0.50,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['7', '10'],
    weight: '30ml',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-23: Nápoje
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-91',
    categoryId: 'cat-23',
    name: 'Coca-Cola 0.33l',
    nameSk: 'Coca-Cola 0.33l',
    description: 'Klasická Coca-Cola',
    descriptionSk: 'Klasická Coca-Cola',
    price: 1.80,
    image: '/images/hero-bg.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: [],
    weight: '0.33l',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-92',
    categoryId: 'cat-23',
    name: 'Sprite 0.33l',
    nameSk: 'Sprite 0.33l',
    description: 'Osviežujúci Sprite',
    descriptionSk: 'Osviežujúci Sprite',
    price: 1.80,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: [],
    weight: '0.33l',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-93',
    categoryId: 'cat-23',
    name: 'Fuze Tea 0.33l',
    nameSk: 'Fuze Tea 0.33l',
    description: 'Ľadový čaj Fuze Tea',
    descriptionSk: 'Ľadový čaj Fuze Tea',
    price: 1.80,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: [],
    weight: '0.33l',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-94',
    categoryId: 'cat-23',
    name: 'Zlatý bažant 0.5l',
    nameSk: 'Zlatý bažant 0.5l',
    description: 'Slovenský ležiak Zlatý bažant',
    descriptionSk: 'Slovenský ležiak Zlatý bažant',
    price: 2.50,
    image: '/images/hero-bg.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1'],
    weight: '0.5l',
    isAlcohol: true,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-95',
    categoryId: 'cat-23',
    name: 'Topvar 0.5l',
    nameSk: 'Topvar 0.5l',
    description: 'Slovenské pivo Topvar',
    descriptionSk: 'Slovenské pivo Topvar',
    price: 2.30,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: ['1'],
    weight: '0.5l',
    isAlcohol: true,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },
  {
    id: 'item-96',
    categoryId: 'cat-23',
    name: 'Voda Rajec 0.5l',
    nameSk: 'Voda Rajec 0.5l',
    description: 'Prírodná minerálna voda Rajec',
    descriptionSk: 'Prírodná minerálna voda Rajec',
    price: 1.50,
    image: '/images/hero-bg.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: false,
    isVegetarian: true,
    isAvailable: true,
    allergens: [],
    weight: '0.5l',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // cat-24: Nočný rozvoz
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'item-97',
    categoryId: 'cat-24',
    name: 'Nočný burger',
    nameSk: 'Nočný burger',
    description: 'Hovädzí burger so slaninou, cheddarom a špeciálnou omáčkou – nočná edícia',
    descriptionSk: 'Hovädzí burger so slaninou, cheddarom a špeciálnou omáčkou – nočná edícia',
    price: 10.90,
    image: '/images/burger.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '320g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...sideAddons, ...extraAddons, ...spiceAddons],
  },
  {
    id: 'item-98',
    categoryId: 'cat-24',
    name: 'Nočný kebab',
    nameSk: 'Nočný kebab',
    description: 'Veľký kebab s extra omáčkou – ideálny na neskorú noc',
    descriptionSk: 'Veľký kebab s extra omáčkou – ideálny na neskorú noc',
    price: 9.50,
    image: '/images/kebab.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7', '11'],
    weight: '400g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-99',
    categoryId: 'cat-24',
    name: 'Nočný box: Burger + hranolky + pivo',
    nameSk: 'Nočný box: Burger + hranolky + pivo',
    description: 'Kompletný nočný box s burgerom, hranolkami a pivom Zlatý bažant',
    descriptionSk: 'Kompletný nočný box s burgerom, hranolkami a pivom Zlatý bažant',
    price: 14.90,
    image: '/images/menu-box.jpg',
    isPopular: true,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '700g',
    isAlcohol: true,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
  {
    id: 'item-100',
    categoryId: 'cat-24',
    name: 'Nočné krídla box',
    nameSk: 'Nočné krídla box',
    description: '12 krídiel v BBQ omáčke s hranolkami – nočná porcia',
    descriptionSk: '12 krídiel v BBQ omáčke s hranolkami – nočná porcia',
    price: 11.90,
    image: '/images/chicken-wings.jpg',
    isPopular: false,
    isSpicy: false,
    isNew: true,
    isVegetarian: false,
    isAvailable: true,
    allergens: ['1', '3', '7'],
    weight: '500g',
    isAlcohol: false,
    isDailyMenu: false,
    isWeeklySpecial: false,
    isDailyDeal: false,
    addons: [...dressingAddons, ...spiceAddons],
  },
]

// ─── Allergen map (Slovak) ────────────────────────────────────────────────────

export const allergenMap: Record<string, string> = {
  '1': 'Obilniny (glutén)',
  '2': 'Kôrovce',
  '3': 'Vajcia',
  '4': 'Ryby',
  '5': 'Arašidy',
  '6': 'Sójové bôby',
  '7': 'Mlieko',
  '8': 'Orechy',
  '9': 'Zeler',
  '10': 'Horčica',
  '11': 'Sezam',
  '12': 'Oxid siričitý',
  '13': 'Vlčí bob',
  '14': 'Mäkkýše',
}

// ─── Opening hours ─────────────────────────────────────────────────────────────

export const openingHours = [
  { day: 'Po', hours: 'Zatvorené', isClosed: true },
  { day: 'Ut', hours: '11:30 – 22:20' },
  { day: 'St', hours: '11:30 – 22:20' },
  { day: 'Št', hours: '11:30 – 22:20' },
  { day: 'Pi', hours: '12:00 – 01:00' },
  { day: 'So', hours: '12:30 – 01:00' },
  { day: 'Ne', hours: '14:00 – 22:00' },
]

// ─── Delivery zones (21) ──────────────────────────────────────────────────────

export interface DeliveryZoneData {
  name: string
  fee: number
  minOrder: number
  freeDeliveryThreshold: number
  time: string
}

export const deliveryZones: DeliveryZoneData[] = [
  { name: 'Hlohovec', fee: 1.00, minOrder: 5, freeDeliveryThreshold: 15, time: '20-30 min' },
  { name: 'Šulekovo', fee: 2.50, minOrder: 15, freeDeliveryThreshold: 0, time: '30-40 min' },
  { name: 'Kľačany', fee: 2.50, minOrder: 15, freeDeliveryThreshold: 0, time: '30-40 min' },
  { name: 'Madunice', fee: 2.50, minOrder: 15, freeDeliveryThreshold: 0, time: '30-40 min' },
  { name: 'Červeník', fee: 3.00, minOrder: 15, freeDeliveryThreshold: 0, time: '35-45 min' },
  { name: 'Leopoldov', fee: 2.50, minOrder: 12, freeDeliveryThreshold: 0, time: '25-35 min' },
  { name: 'Sereď', fee: 3.00, minOrder: 15, freeDeliveryThreshold: 0, time: '35-50 min' },
  { name: 'Sládkovičovo', fee: 3.50, minOrder: 15, freeDeliveryThreshold: 0, time: '40-50 min' },
  { name: 'Vinohrady nad Váhom', fee: 2.50, minOrder: 15, freeDeliveryThreshold: 0, time: '30-40 min' },
  { name: 'Tvrdomestice', fee: 3.00, minOrder: 15, freeDeliveryThreshold: 0, time: '35-45 min' },
  { name: 'Piešťany', fee: 4.00, minOrder: 20, freeDeliveryThreshold: 0, time: '40-55 min' },
  { name: 'Banka', fee: 4.00, minOrder: 20, freeDeliveryThreshold: 0, time: '40-55 min' },
  { name: 'Ratnovce', fee: 3.50, minOrder: 15, freeDeliveryThreshold: 0, time: '35-50 min' },
  { name: 'Hubina', fee: 3.50, minOrder: 15, freeDeliveryThreshold: 0, time: '35-50 min' },
  { name: 'Pečeňady', fee: 3.00, minOrder: 15, freeDeliveryThreshold: 0, time: '35-45 min' },
  { name: 'Hradište', fee: 2.50, minOrder: 12, freeDeliveryThreshold: 0, time: '25-35 min' },
  { name: 'Dolné Otrokovce', fee: 2.50, minOrder: 15, freeDeliveryThreshold: 0, time: '30-40 min' },
  { name: 'Horné Otrokovce', fee: 2.50, minOrder: 15, freeDeliveryThreshold: 0, time: '30-40 min' },
  { name: 'Trnava', fee: 5.00, minOrder: 25, freeDeliveryThreshold: 0, time: '45-60 min' },
  { name: 'Bíňovce', fee: 3.00, minOrder: 15, freeDeliveryThreshold: 0, time: '35-45 min' },
  { name: 'Križovany nad Dudváhom', fee: 3.00, minOrder: 15, freeDeliveryThreshold: 0, time: '35-45 min' },
]

// ─── Mock orders for admin ─────────────────────────────────────────────────────

export interface MockOrder {
  id: string
  orderNumber: string
  status: string
  customerName: string
  customerPhone: string
  deliveryType: 'DELIVERY' | 'PICKUP'
  address: string
  items: { name: string; quantity: number; price: number }[]
  total: number
  paymentMethod: string
  notes: string
  createdAt: string
  estimatedTime: string
}

export const mockOrders: MockOrder[] = [
  {
    id: 'ord-1',
    orderNumber: 'DSF-001',
    status: 'PREPARING',
    customerName: 'Ján Novák',
    customerPhone: '+421 912 345 678',
    deliveryType: 'DELIVERY',
    address: 'Hlavná 15, Hlohovec',
    items: [
      { name: 'Dragon Burger', quantity: 2, price: 9.90 },
      { name: 'Hranolky', quantity: 1, price: 2.90 },
    ],
    total: 22.70,
    paymentMethod: 'Hotovosť pri doručení',
    notes: 'Bez cibule prosím',
    createdAt: '12:30',
    estimatedTime: '13:05',
  },
  {
    id: 'ord-2',
    orderNumber: 'DSF-002',
    status: 'ACCEPTED',
    customerName: 'Mária Kováčová',
    customerPhone: '+421 918 765 432',
    deliveryType: 'PICKUP',
    address: '',
    items: [
      { name: 'Kebab v chlebe', quantity: 1, price: 7.50 },
      { name: 'Coca-Cola 0.33l', quantity: 2, price: 1.80 },
    ],
    total: 11.10,
    paymentMethod: 'Platba pri prevzatí',
    notes: '',
    createdAt: '12:35',
    estimatedTime: '13:10',
  },
  {
    id: 'ord-3',
    orderNumber: 'DSF-003',
    status: 'OUT_FOR_DELIVERY',
    customerName: 'Peter Horváth',
    customerPhone: '+421 905 111 222',
    deliveryType: 'DELIVERY',
    address: 'Školská 8, Hlohovec',
    items: [
      { name: 'Pinsa Quattro Formaggi', quantity: 1, price: 10.90 },
      { name: 'Kuracie krídla BBQ', quantity: 1, price: 8.50 },
      { name: 'Churros s čokoládou', quantity: 1, price: 4.90 },
    ],
    total: 24.30,
    paymentMethod: 'Online platba',
    notes: 'Zvoniť, nie klipnúť',
    createdAt: '12:10',
    estimatedTime: '12:55',
  },
  {
    id: 'ord-4',
    orderNumber: 'DSF-004',
    status: 'CREATED',
    customerName: 'Anna Slobodová',
    customerPhone: '+421 911 333 444',
    deliveryType: 'DELIVERY',
    address: 'Nábrežie 22, Hlohovec',
    items: [
      { name: 'Chili Cheese Dog', quantity: 1, price: 6.90 },
      { name: 'Kapsalón kurací', quantity: 1, price: 10.90 },
    ],
    total: 17.80,
    paymentMethod: 'Hotovosť pri doručení',
    notes: '',
    createdAt: '12:42',
    estimatedTime: '13:20',
  },
  {
    id: 'ord-5',
    orderNumber: 'DSF-005',
    status: 'COURIER_ON_WAY',
    customerName: 'Martin Bartoš',
    customerPhone: '+421 907 555 666',
    deliveryType: 'DELIVERY',
    address: 'Hviezdoslavova 3, Leopoldov',
    items: [
      { name: 'Double Smash Burger', quantity: 1, price: 11.90 },
      { name: 'Belgické hranolky', quantity: 1, price: 3.50 },
      { name: 'Zlatý bažant 0.5l', quantity: 2, price: 2.50 },
    ],
    total: 20.40,
    paymentMethod: 'Online platba',
    notes: 'Nechajte pred dvermi',
    createdAt: '12:15',
    estimatedTime: '13:00',
  },
  {
    id: 'ord-6',
    orderNumber: 'DSF-006',
    status: 'PROBLEM',
    customerName: 'Zuzana Králiková',
    customerPhone: '+421 903 777 888',
    deliveryType: 'DELIVERY',
    address: 'Mlynská 7, Hlohovec',
    items: [
      { name: 'Denné menu: Burger + polievka + nápoj', quantity: 2, price: 9.90 },
    ],
    total: 19.80,
    paymentMethod: 'Hotovosť pri doručení',
    notes: 'Kuriér nenašiel adresu',
    createdAt: '11:50',
    estimatedTime: '12:30',
  },
]

// ─── Mock couriers ─────────────────────────────────────────────────────────────

export interface MockCourier {
  id: string
  name: string
  phone: string
  isAvailable: boolean
  isOnline: boolean
  vehicleType: string
  activeOrders: number
  location: string
}

export const mockCouriers: MockCourier[] = [
  { id: 'courier-1', name: 'Milan Števko', phone: '+421 912 000 111', isAvailable: true, isOnline: true, vehicleType: 'Auto', activeOrders: 1, location: 'Hlohovec centrum' },
  { id: 'courier-2', name: 'Tomáš Bielik', phone: '+421 915 000 222', isAvailable: true, isOnline: true, vehicleType: 'Bicykel', activeOrders: 0, location: 'Pri reštaurácii' },
  { id: 'courier-3', name: 'Lukáš Hraško', phone: '+421 918 000 333', isAvailable: false, isOnline: false, vehicleType: 'Auto', activeOrders: 2, location: 'Leopoldov' },
]

// ─── Order status labels (Slovak) ─────────────────────────────────────────────

export const statusLabels: Record<string, { label: string; color: string; icon: string }> = {
  CREATED: { label: 'Vytvorená', color: 'bg-gray-100 text-gray-700', icon: '📋' },
  PAYMENT_PENDING: { label: 'Čaká na platbu', color: 'bg-yellow-100 text-yellow-700', icon: '💳' },
  PAID: { label: 'Zaplatená', color: 'bg-blue-100 text-blue-700', icon: '✅' },
  ACCEPTED: { label: 'Prijatá', color: 'bg-blue-100 text-blue-700', icon: '👍' },
  REJECTED: { label: 'Odmietnutá', color: 'bg-red-100 text-red-700', icon: '❌' },
  PREPARING: { label: 'Pripravuje sa', color: 'bg-orange-100 text-orange-700', icon: '🍳' },
  READY_FOR_PICKUP: { label: 'Pripravená na vyzdvihnutie', color: 'bg-green-100 text-green-700', icon: '✨' },
  COURIER_ASSIGNED: { label: 'Kuriér pridelený', color: 'bg-purple-100 text-purple-700', icon: '🚗' },
  COURIER_ON_WAY: { label: 'Kuriér ide do prevádzky', color: 'bg-purple-100 text-purple-700', icon: '🚶' },
  PICKED_UP: { label: 'Vyzdvihnutá', color: 'bg-purple-100 text-purple-700', icon: '📦' },
  OUT_FOR_DELIVERY: { label: 'Na ceste k vám', color: 'bg-dragon-red/10 text-dragon-red', icon: '🛵' },
  DELIVERED: { label: 'Doručená', color: 'bg-green-100 text-green-700', icon: '🏠' },
  COMPLETED: { label: 'Dokončená', color: 'bg-green-100 text-green-700', icon: '🎉' },
  CANCELLED: { label: 'Zrušená', color: 'bg-red-100 text-red-700', icon: '🚫' },
  REFUNDED: { label: 'Vrátená', color: 'bg-gray-100 text-gray-700', icon: '💰' },
  PROBLEM: { label: 'Problém s objednávkou', color: 'bg-red-100 text-red-700', icon: '⚠️' },
}
